export const data = [
  {
    featureID: 1,
    name: "9004 - Anular pedidos de destacamento e determinação de legislação",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9004_ffta_anular_pedido.feature",
    tags: [
      "@browser",
      "@auth",
      "@ffta",
      "@ffta9004",
      "@DLA_anular",
      "@job_noturno",
    ],
    result: {
      duration: "24m:47s",
      scenariosPassed: 1,
      scenariosSkipped: 0,
      scenariosFailed: 55,
      scenariosTotal: 56,
    },
  },
  {
    _id: "6631cb20e291f93a773e49f5",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 2,
    name: "9009 - Consultar detalhe de um pedido de destacamento ou de determinação de legislação",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9009_ffta_consultarDetalhe_pedido.feature",
    tags: [
      "@browser",
      "@auth",
      "@ffta",
      "@ffta9009",
      "@DLA_consultarDetalhe",
      "@job_noturno",
    ],
    result: {
      duration: "32m:36s",
      scenariosPassed: 36,
      scenariosSkipped: 0,
      scenariosFailed: 44,
      scenariosTotal: 80,
    },
  },
  {
    _id: "6631cb24e291f93a773e4d80",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 3,
    name: "9012 - Emitir comprovativo de um pedido",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9012_ffta_emitirComprovativo_pedido.feature",
    tags: [
      "@browser",
      "@auth",
      "@ffta",
      "@ffta9012",
      "@DLA_emitirComprovativo",
      "@job_noturno",
    ],
    result: {
      duration: "32m:26s",
      scenariosPassed: 44,
      scenariosSkipped: 0,
      scenariosFailed: 37,
      scenariosTotal: 81,
    },
  },
  {
    _id: "6631cb25e291f93a773e4ec7",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 4,
    name: "9027 - Registo de novo pedido de determinação de legislação para trabalhadores por conta de outrem",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9027_ffta_registoOutrosTCO.feature",
    tags: ["@browser", "@auth", "@DLA_registoOutrosTCO", "@job_noturno"],
    result: {
      duration: "18m:43s",
      scenariosPassed: 3,
      scenariosSkipped: 4,
      scenariosFailed: 10,
      scenariosTotal: 17,
    },
  },
  {
    _id: "6631cb28e291f93a773e519f",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 5,
    name: "9028 - Registo de novo pedido de destacamento para trabalhadores por conta de outrem",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9028_ffta_registoTCO.feature",
    tags: ["@browser", "@auth", "@DLA_registoTCO", "@job_noturno"],
    result: {
      duration: "41m:41s",
      scenariosPassed: 15,
      scenariosSkipped: 0,
      scenariosFailed: 8,
      scenariosTotal: 23,
    },
  },
  {
    _id: "6631cb28e291f93a773e52b4",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 6,
    name: "9029 - Registo de novo pedido de destacamento para trabalhadores independentes",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9029_ffta_registoTI.feature",
    tags: [
      "@browser",
      "@ffta",
      "@ffta9029",
      "@auth",
      "@registo2-destacamento_TI",
      "@job_noturno",
    ],
    result: {
      duration: "25m:14s",
      scenariosPassed: 4,
      scenariosSkipped: 0,
      scenariosFailed: 9,
      scenariosTotal: 13,
    },
  },
  {
    _id: "6631cb29e291f93a773e5367",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 7,
    name: "9030 - Registo de novo pedido de determinação de legislação para trabalhadores independentes",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9030_ffta_registoTIVarios.feature",
    tags: ["@browser", "@ffta", "@ffta9030", "@auth", "@job_noturno"],
    result: {
      duration: "4m:20s",
      scenariosPassed: 1,
      scenariosSkipped: 0,
      scenariosFailed: 10,
      scenariosTotal: 11,
    },
  },
  {
    _id: "6631cb2ae291f93a773e5497",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 8,
    name: "9031 - Registo de novo pedido de determinação de legislação para trabalhadores de transportes internacionais",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9031_ffta_registoTransportes.feature",
    tags: ["@browser", "@auth", "@job_noturno"],
    result: {
      duration: "15m:2s",
      scenariosPassed: 8,
      scenariosSkipped: 4,
      scenariosFailed: 5,
      scenariosTotal: 17,
    },
  },
  {
    _id: "6631cb2be291f93a773e56d7",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 9,
    name: "9032 - Registo de novo pedido de determinação de legislação para tripulantes de voo e cabine",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9032_ffta_registoTripulantes.feature",
    tags: ["@browser", "@ffta", "@ffta9032", "@auth", "@job_noturno"],
    result: {
      duration: "25m:26s",
      scenariosPassed: 1,
      scenariosSkipped: 7,
      scenariosFailed: 24,
      scenariosTotal: 32,
    },
  },
  {
    _id: "6631cb2ce291f93a773e57ba",
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    featureID: 10,
    name: "9033 - Reserva de diferentes pedidos de destacamento ou de determinação de legislação",
    uri: "classpath:features/9000_ffta_feature_file_testes_automatizados/9033_ffta_reservar_pedido.feature",
    tags: [
      "@browser",
      "@auth",
      "@ffta",
      "@ffta9033",
      "@DLA_reservar",
      "@job_noturno",
    ],
    result: {
      duration: "8m:29s",
      scenariosPassed: 7,
      scenariosSkipped: 0,
      scenariosFailed: 9,
      scenariosTotal: 16,
    },
  },
];

export const featureData = [
  {
    execID: "bc7488be783f4b5d81cad025b0b8ee5c",
    date: "2024-05-01 05:55",
    environ: "dev",
    version: "5.47.0-SNAPSHOT",
    module: "it-dla-browser",
    result: {
      duration: "3h:48m:48s",
      scenariosPassed: 120,
      scenariosSkipped: 15,
      scenariosFailed: 211,
      scenariosPending: 0,
      scenariosUndefined: 0,
      scenariosAmbiguous: 0,
      scenariosTotal: 346,
    },
    dashboardName: "jobNoturno",
  },
];
